// <auto-generated />
using CursorPagingApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CursorPagingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250302200936_InitCommit")]
    partial class InitCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CursorPagingApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Clothing",
                            Name = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Toys",
                            Name = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            Name = "Product 3"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Clothing",
                            Name = "Product 4"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Toys",
                            Name = "Product 5"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            Name = "Product 6"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Clothing",
                            Name = "Product 7"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Toys",
                            Name = "Product 8"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Electronics",
                            Name = "Product 9"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Clothing",
                            Name = "Product 10"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Toys",
                            Name = "Product 11"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Electronics",
                            Name = "Product 12"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Clothing",
                            Name = "Product 13"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Toys",
                            Name = "Product 14"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Electronics",
                            Name = "Product 15"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Clothing",
                            Name = "Product 16"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Toys",
                            Name = "Product 17"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Electronics",
                            Name = "Product 18"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Clothing",
                            Name = "Product 19"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Toys",
                            Name = "Product 20"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Electronics",
                            Name = "Product 21"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Clothing",
                            Name = "Product 22"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Toys",
                            Name = "Product 23"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Electronics",
                            Name = "Product 24"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Clothing",
                            Name = "Product 25"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Toys",
                            Name = "Product 26"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Electronics",
                            Name = "Product 27"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Clothing",
                            Name = "Product 28"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Toys",
                            Name = "Product 29"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Electronics",
                            Name = "Product 30"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Clothing",
                            Name = "Product 31"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Toys",
                            Name = "Product 32"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Electronics",
                            Name = "Product 33"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Clothing",
                            Name = "Product 34"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Toys",
                            Name = "Product 35"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Electronics",
                            Name = "Product 36"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Clothing",
                            Name = "Product 37"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Toys",
                            Name = "Product 38"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Electronics",
                            Name = "Product 39"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Clothing",
                            Name = "Product 40"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Toys",
                            Name = "Product 41"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Electronics",
                            Name = "Product 42"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Clothing",
                            Name = "Product 43"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Toys",
                            Name = "Product 44"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Electronics",
                            Name = "Product 45"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Clothing",
                            Name = "Product 46"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Toys",
                            Name = "Product 47"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Electronics",
                            Name = "Product 48"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Clothing",
                            Name = "Product 49"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Toys",
                            Name = "Product 50"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Electronics",
                            Name = "Product 51"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Clothing",
                            Name = "Product 52"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Toys",
                            Name = "Product 53"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Electronics",
                            Name = "Product 54"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Clothing",
                            Name = "Product 55"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Toys",
                            Name = "Product 56"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Electronics",
                            Name = "Product 57"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Clothing",
                            Name = "Product 58"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Toys",
                            Name = "Product 59"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Electronics",
                            Name = "Product 60"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Clothing",
                            Name = "Product 61"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Toys",
                            Name = "Product 62"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Electronics",
                            Name = "Product 63"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Clothing",
                            Name = "Product 64"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Toys",
                            Name = "Product 65"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Electronics",
                            Name = "Product 66"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Clothing",
                            Name = "Product 67"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Toys",
                            Name = "Product 68"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Electronics",
                            Name = "Product 69"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Clothing",
                            Name = "Product 70"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Toys",
                            Name = "Product 71"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Electronics",
                            Name = "Product 72"
                        },
                        new
                        {
                            Id = 73,
                            Category = "Clothing",
                            Name = "Product 73"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Toys",
                            Name = "Product 74"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Electronics",
                            Name = "Product 75"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Clothing",
                            Name = "Product 76"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Toys",
                            Name = "Product 77"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Electronics",
                            Name = "Product 78"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Clothing",
                            Name = "Product 79"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Toys",
                            Name = "Product 80"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Electronics",
                            Name = "Product 81"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Clothing",
                            Name = "Product 82"
                        },
                        new
                        {
                            Id = 83,
                            Category = "Toys",
                            Name = "Product 83"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Electronics",
                            Name = "Product 84"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Clothing",
                            Name = "Product 85"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Toys",
                            Name = "Product 86"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Electronics",
                            Name = "Product 87"
                        },
                        new
                        {
                            Id = 88,
                            Category = "Clothing",
                            Name = "Product 88"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Toys",
                            Name = "Product 89"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Electronics",
                            Name = "Product 90"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Clothing",
                            Name = "Product 91"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Toys",
                            Name = "Product 92"
                        },
                        new
                        {
                            Id = 93,
                            Category = "Electronics",
                            Name = "Product 93"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Clothing",
                            Name = "Product 94"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Toys",
                            Name = "Product 95"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Electronics",
                            Name = "Product 96"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Clothing",
                            Name = "Product 97"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Toys",
                            Name = "Product 98"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Electronics",
                            Name = "Product 99"
                        },
                        new
                        {
                            Id = 100,
                            Category = "Clothing",
                            Name = "Product 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
